-- Create databases
CREATE DATABASE flight_data_2015;
CREATE DATABASE flight_data_2022;
CREATE DATABASE flight_data_2023;
GO

-- Use flight_data_year
USE flight_data_2015;
-- USE flight_data_2022;
-- USE flight_data_2023;
GO

-- Create AIRPORT table
CREATE TABLE AIRPORT (
    IATA_CODE VARCHAR(10) PRIMARY KEY,
    AIRPORT NVARCHAR(100),
    CITY NVARCHAR(50),
    STATE NVARCHAR(50)
);
GO

-- Create AIRLINE table
CREATE TABLE AIRLINE (
    IATA_CODE VARCHAR(10) PRIMARY KEY,
    AIRLINE NVARCHAR(100)
);
GO

-- Create FLIGHT table
CREATE TABLE FLIGHT (
    FLIGHT_ID INT IDENTITY(1,1) PRIMARY KEY,
    YEAR INT,
    MONTH INT,
    DAY INT,
    AIRLINE VARCHAR(10),
    TAIL_NUMBER VARCHAR(20),
    ORIGIN_AIRPORT VARCHAR(10),
    DESTINATION_AIRPORT VARCHAR(10),
    DISTANCE INT,
    ARRIVAL_DELAY INT,
    DEPARTURE_DELAY INT,
    CANCELLED BIT,  -- Use BIT for boolean-like flags in SQL Server
    DEPARTURE_TIME TIME,
    CANCELLATION_REASON NVARCHAR(50),
    FOREIGN KEY (AIRLINE) REFERENCES AIRLINE(IATA_CODE),
    FOREIGN KEY (ORIGIN_AIRPORT) REFERENCES AIRPORT(IATA_CODE),
    FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES AIRPORT(IATA_CODE)
);
GO
